import HeaderComponnent from '@/components/header/header'
import './globals.css'
import { Inter } from 'next/font/google'
import FooterComponnent from '@/components/footer/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'sneaker-cuti',
  description: 'Generated by sneaker-cuti',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="max-w-screen-xl mx-auto px-4 ">
        <HeaderComponnent/>
        {children}
        <FooterComponnent/>
      </body>
    </html>
  )
}
